title: Neo TITANIUM GLOBAL ENERGY
description: >- 
  Static website for Neo Titanium Global Energy with services, team, projects, and partner info.
baseurl: "/neo-titanium-global-enery"
url: "" # the base hostname & protocol for your site, e.g. http://example.com

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge
permalink: pretty

# Exclude from processing
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
